# The URL the site will be built for
base_url = "https://energeticky.report"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[[extra.benefits]]
image = "images/effectivity.svg"
alt = "Efektivnost"
title = "Mobilní řešení"
description = "Mobilní řešení, které je kdykoliv snadno přenositelné na další stroje ve vašem podniku."

[[extra.benefits]]
image = "images/consumption.svg"
alt = "Spotřeba"
title = "Bezpečná komunikace"
description = "Zařízení komunikují bezdrátově, bezpečně a nezávisle na vaší interní síti."


[[extra.benefits]]
image = "images/time-effectivity.svg"
alt = "Efektivita"
title = "Rychle a bezstarostně"
description = "Instalaci začneme do 30 dnů a potrvá jen desítky minut. Provoz omezíme minimálně, nebo vůbec."

[[extra.benefits]]
image = "images/document.svg"
alt = "Spotřeba"
title = "Okamžitá data z provozu"
description = "Ihned po instalaci uvidíte data z výroby ve vašem telefonu i počítači."



[[extra.steps]]
number = "1"
title = "Online schůzka"
description = "Vyplňte formulář níže, ozveme se vám a společně domluvíme termín online schůzky. Na ní probereme, jak program funguje, vaše dotazy a společně vybereme jak budeme spotřebu monitorovat."

[[extra.steps]]
number = "2"
title = " Nasazení - zahájení pilotu"
description = "Do 30 dnů u vás senzory nainstalujeme a integrujeme je s vybranými aplikacemi. Instalace zabere jen pár desítek minut a okamžitě budete mít k dispozici data o spotřebě energií."
button = "Zobrazit ukázku reportu"

[[extra.steps]]
number = "3"
title = "Sledování a vyhodnocení"
description = "Data o spotřebě budete mít okamžitě ve svém počítači i telefonu. Společně se na data podíváme, vyhodnotíme přínosy a pobavíme se o dalších možnostech nasazení a rozšíření IoT monitoringu."



[[extra.faqs]]
question = "Jak funguje program Energeticky.report?"
answer = "Po odeslání formuláře vás oslovíme, abychom si domluvili termín online schůzky. Během ní odpovíme na vaše dotazy a společně vybereme nejvhodnější způsob měření spotřeby energií."

[[extra.faqs]]
question = "Lze program rozšířit o další zařízení?"
answer = "Ano, program je kdykoli možné rozšířit o další zařízení podle vašich potřeb."

[[extra.faqs]]
question = "Jak probíhá přenos dat o výrobě? Je to bezpečné?"
answer = "Data přenášíme bezdrátovými sítěmi NB-IoT a LTE-M, které mají výborné pokrytí i uvnitř továren. Tyto sítě jsou zcela nezávislé na vaší interní síti a přenos dat je plně zabezpečený."

[[extra.faqs]]
question = "Kde uvidíme data?"
answer = "Data můžete sledovat v přehledných dashboardech na počítači i telefonu. Nabízíme vlastní řešení, které sami hostujeme, a zároveň ho můžeme integrovat přímo do vašeho systému podle vašich potřeb."

